[package]
name = "client"
version = "0.2.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
once_cell = "1.19.0"
regex = "1.10.4"

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread", "signal"]

[dev-dependencies]
rstest = "0.18.2"
