version: '3.8'
services:
  aira:
    container_name: aira
    restart: always
    volumes:
      - ./config/resolv.conf:/etc/resolv.conf:ro
    image: netetra/aira:latest
    #build: .
    env_file:
      - .env
    networks:
      - aira-network

networks:
  aira-network:
    name: aira-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
