version: "3.9"

services:
  client:
    container_name: client
    build: ./client
    restart: always
    env_file:
      - .env.client
    networks:
      - aira-network
  api:
    container_name: api
    build: ./api
    restart: always
    env_file:
      - .env.api
    ports:
      - 3000:3000
    networks:
      - aira-network

networks:
  aira-network:
    name: aira-network
    driver: bridge
