FROM rust:1.76.0-slim-bookworm as builder

WORKDIR /build

COPY . .

RUN cargo build --release

FROM gcr.io/distroless/cc-debian12

WORKDIR /app

COPY --from=builder /build/target/release/api ./

CMD ["./api"]
